### ISSUE TITLE
Request: Identity Framework Deployer

### ISSUE THREAD

**Issue by basmilius** [basmilius/bas-tools#12]
**Stage 1: Add Deployer functionality to bas-tools**
- [ ] List with projects, make them launch-able from a tool window or such.
- [ ] Compilers
  - [ ] Sass / Scss
  - [ ] JavaScript / TypeScript
- [ ] Create new project using our existing templates.

.

**Stage 2: Make these functionalities standalone, without the use of our deployer**
- [ ] Remove connection between bas-tools and deployer.
- [ ] Create live reloading protocol with "override-properties" support.
- [ ] Create project from bas-tools.
- [ ] Add connection to deployer database.
